//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfentHandler.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class answer
    {
        public int AnswerId { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<int> IntAnswer { get; set; }
        public string TextAnswer { get; set; }
        public Nullable<int> MultipleChoiceAnswer { get; set; }
        public int SurveyQuestionId { get; set; }
        public Nullable<int> QuestionChoiceId { get; set; }
        public Nullable<int> QuestionChoiceId2 { get; set; }
    
        public virtual multiplechoiceanswer multiplechoiceanswer1 { get; set; }
        public virtual question_choice question_choice { get; set; }
        public virtual question_choice question_choice1 { get; set; }
        public virtual survey_question survey_question { get; set; }
    }
}
