//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfentHandler.Domain.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EfentHandlerEntities : DbContext
    {
        public EfentHandlerEntities()
            : base("name=EfentHandlerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<answer> answer { get; set; }
        public virtual DbSet<assignment> assignment { get; set; }
        public virtual DbSet<availability> availability { get; set; }
        public virtual DbSet<chart_type> chart_type { get; set; }
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<contactperson> contactperson { get; set; }
        public virtual DbSet<multiplechoiceanswer> multiplechoiceanswer { get; set; }
        public virtual DbSet<question> question { get; set; }
        public virtual DbSet<question_choice> question_choice { get; set; }
        public virtual DbSet<questiontype> questiontype { get; set; }
        public virtual DbSet<request> request { get; set; }
        public virtual DbSet<schedule> schedule { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<survey> survey { get; set; }
        public virtual DbSet<survey_question> survey_question { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<user_assignment> user_assignment { get; set; }
        public virtual DbSet<usertype> usertype { get; set; }
    }
}
