//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfentHandler.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public question()
        {
            this.multiplechoiceanswer = new HashSet<multiplechoiceanswer>();
            this.question_choice = new HashSet<question_choice>();
            this.survey_question = new HashSet<survey_question>();
        }
    
        public int QuestionId { get; set; }
        public string Question1 { get; set; }
        public string Image { get; set; }
        public int QuestionTypeId { get; set; }
        public int EditedByEmployee { get; set; }
        public Nullable<int> ChartTypeId { get; set; }
    
        public virtual chart_type chart_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<multiplechoiceanswer> multiplechoiceanswer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<question_choice> question_choice { get; set; }
        public virtual questiontype questiontype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<survey_question> survey_question { get; set; }
    }
}
