//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfentHandler.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule
    {
        public int ScheduleId { get; set; }
        public int Inspector { get; set; }
        public int Confirmed { get; set; }
        public int AssignmentId { get; set; }
    
        public virtual assignment assignment { get; set; }
        public virtual user user { get; set; }
    }
}
