//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfentHandler.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class survey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public survey()
        {
            this.survey_question = new HashSet<survey_question>();
            this.survey1 = new HashSet<survey>();
        }
    
        public int SurveyId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> ConfirmedByEmployee { get; set; }
        public Nullable<bool> ConfirmedByInspector { get; set; }
        public bool IsTemplate { get; set; }
        public Nullable<int> ParentSurvey { get; set; }
        public Nullable<int> AssignmentId { get; set; }
        public Nullable<int> AssignedEmployee { get; set; }
    
        public virtual assignment assignment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<survey_question> survey_question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<survey> survey1 { get; set; }
        public virtual survey survey2 { get; set; }
        public virtual user user { get; set; }
    }
}
