INSERT INTO multiplechoiceanswer ([Answer], [QuestionId])
VALUES ('Geen rij', 7)
INSERT INTO multiplechoiceanswer ([Answer], [QuestionId])
VALUES ('1-10 minuten', 7)
INSERT INTO multiplechoiceanswer ([Answer], [QuestionId])
VALUES ('10-30 minuten', 7)
INSERT INTO multiplechoiceanswer ([Answer], [QuestionId])
VALUES ('Langer dan 30 minuten', 7)
INSERT INTO multiplechoiceanswer ([Answer], [QuestionId])
VALUES ('Avicii', 9)
INSERT INTO multiplechoiceanswer ([Answer], [QuestionId])
VALUES ('Hardwell', 9)
INSERT INTO multiplechoiceanswer ([Answer], [QuestionId])
VALUES ('Don Diablo', 9)
INSERT INTO multiplechoiceanswer ([Answer], [QuestionId])
VALUES ('Snollebollekes', 9)