INSERT INTO question ([Question],[Image], [QuestionTypeId], [EditedByEmployee], [ChartTypeId])
VALUES ('Hoe vies waren de W.C.s?', null, 1, 1, null)
INSERT INTO question ([Question],[Image], [QuestionTypeId], [EditedByEmployee], [ChartTypeId])
VALUES ('Werd er alcohol onder de 18 geschonken?', null, 2, 1, null)
INSERT INTO question ([Question],[Image], [QuestionTypeId], [EditedByEmployee], [ChartTypeId])
VALUES ('Maak een foto van de W.C.', null, 3, 1, null)
INSERT INTO question ([Question],[Image], [QuestionTypeId], [EditedByEmployee], [ChartTypeId])
VALUES ('Meet de afstand tussen 2 acts', null, 4, 1, null)
INSERT INTO question ([Question],[Image], [QuestionTypeId], [EditedByEmployee], [ChartTypeId])
VALUES ('Teken de looplijnen van het festival', null, 5, 1, null)
INSERT INTO question ([Question],[Image], [QuestionTypeId], [EditedByEmployee], [ChartTypeId])
VALUES ('Tel hoeveel tafels er staan per eettent', null, 6, 1, null)
INSERT INTO question ([Question],[Image], [QuestionTypeId], [EditedByEmployee], [ChartTypeId])
VALUES ('Hoe lang was de rij bij de wcs?', null, 7, 1, null)
INSERT INTO question ([Question],[Image], [QuestionTypeId], [EditedByEmployee], [ChartTypeId])
VALUES ('Hoe lang is de wachtrij bij de ingang? (Per uur tussen 13:00 en 15:00)', null, 8, 1, null)
INSERT INTO question ([Question],[Image], [QuestionTypeId], [EditedByEmployee], [ChartTypeId])
VALUES ('Hoeveel mensen staan er in de rij per act 5 minuten voor aanvang?', null, 9, 1, null)