INSERT INTO status ([Status])
VALUES ('Start - Open')
INSERT INTO status ([Status])
VALUES ('Wachten op goedkeuring offerte - Open')
INSERT INTO status ([Status])
VALUES ('In voorbereiding - Goedgekeurd')
INSERT INTO status ([Status])
VALUES ('Klaar voor inspectie')
INSERT INTO status ([Status])
VALUES ('Klaar voor oplevering')
INSERT INTO status ([Status])
VALUES ('Gesloten')
INSERT INTO status ([Status])
VALUES ('Gesloten - Afgekeurd')