INSERT INTO survey ([Name], [Date], [ConfirmedByEmployee], [ConfirmedByInspector], [IsTemplate], [ParentSurvey], [AssignmentId], [AssignedEmployee])
VALUES ('Solexrace Lijst 1', '2018-08-29', 1, 0, 0, null, 1, 1)
INSERT INTO survey ([Name], [Date], [ConfirmedByEmployee], [ConfirmedByInspector], [IsTemplate], [ParentSurvey], [AssignmentId], [AssignedEmployee])
VALUES ('Solexrace Lijst 2', '2018-08-30', 1, 1, 0, null, 1, 1)
INSERT INTO survey ([Name], [Date], [ConfirmedByEmployee], [ConfirmedByInspector], [IsTemplate], [ParentSurvey], [AssignmentId], [AssignedEmployee])
VALUES ('Solexrace Lijst Template', null, null, null, 1, null, null, null)