INSERT INTO survey_question ([SurveyId], [QuestionId])
VALUES (1, 1)
INSERT INTO survey_question ([SurveyId], [QuestionId])
VALUES (1, 2)
INSERT INTO survey_question ([SurveyId], [QuestionId])
VALUES (1, 3)
INSERT INTO survey_question ([SurveyId], [QuestionId])
VALUES (1, 4)
INSERT INTO survey_question ([SurveyId], [QuestionId])
VALUES (1, 5)
INSERT INTO survey_question ([SurveyId], [QuestionId])
VALUES (1, 6)
INSERT INTO survey_question ([SurveyId], [QuestionId])
VALUES (1, 7)
INSERT INTO survey_question ([SurveyId], [QuestionId])
VALUES (1, 8)
INSERT INTO survey_question ([SurveyId], [QuestionId])
VALUES (1, 9)
